## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
# Setups
format="$directory$git_branch$character"
right_format = """$git_status$cmd_duration"""
add_newline = false 

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols 
[character]
success_symbol = "[](#9ece6a bold)"
error_symbol = "[](#e0af68)"
vicmd_symbol = "[](#ff9e64)"

[directory]
format = "[]($style)[ ](bg:#24283b fg:#ff9e64)[$path](bg:#24283b fg:#2ac3de bold)[ ]($style)"
style = "bg:none fg:#24283b"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[󰊢 ](bg:#24283b fg:#9ece6a bold)$branch](bg:#24283b fg:#2ac3de)[ ]($style)"
style = "bg:none fg:#24283b"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:#24283b fg:#b4befe)[ ]($style)"
style = "bg:none fg:#24283b"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[󰔚 ](bg:#24283b fg:#f7768e bold)$duration](bg:#24283b fg:#a9b1d6)[ ]($style)"
disabled = false
style = "bg:none fg:#24283b"
